name: food_delivery_app
description: food_delivery_app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.0
code: 7

environment:
  sdk: ">=2.2.2 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  google_maps_flutter: ^0.5.11
  google_map_location_picker: 3.3.3
  mvc_pattern: 6.1.3+2
  global_configuration: 1.5.0
  http: 0.12.2
  html: 0.14.0+3
  shared_preferences: 0.5.8
  flutter_svg: 0.18.0
  location: 3.0.2
  flutter_inappbrowser: 2.0.2
  url_launcher: 5.5.0
  firebase_messaging: ^7.0.3
  cached_network_image: 2.3.0
  flutter_local_notifications: ^4.0.1+1
  fluttertoast: ^7.0.2
  flutter_staggered_grid_view: 0.3.2
  intl_utils: 1.6.3
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1
  flutter_country_picker: ^0.1.6
  flutter_login_facebook: ^0.2.1
#  country_code_picker: ^1.4.0
  permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  platform_device_id: ^0.1.1
  stripe_payment: ^1.0.10
  carousel_slider: ^2.3.1
  http_auth: ^0.3.1
  devicelocale: ^0.3.3
  percent_indicator: ^2.1.7+2
  intl: ^0.16.0
  image_picker: ^0.6.6+5
  fbroadcast: ^1.0.2
  badges: ^1.1.6
  qr_flutter: ^3.1.0
  webview_flutter: ^1.0.7
  location_permissions: ^3.0.0+1
  open_file: ^3.0.3
  dio: ^3.0.10
  flushbar: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  modal_bottom_sheet: ^2.0.0
  flutter_rating_bar: ^4.0.0
  smooth_star_rating: ^1.1.1
  flutter_screenutil: ^3.0.2
  ffi: ^1.0.0
  country_list_pick: ^1.0.1+4



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/
    - assets/img/login.png
    - assets/img/facebook.png
    - assets/img/google.png
    - assets/img/sendIcon.png
    - assets/img/logo.png
    - assets/img/resetIcon.png
    - assets/img/home1.jpg
    - assets/img/home2.jpg
    - assets/img/cart.png
    - assets/img/like.png
    - assets/img/myAccount.png
    - assets/img/helpIcon.png
    - assets/img/settingsIcon.png
    - assets/img/passwordIcon.png
    - assets/img/paymentIcon.png
    - assets/img/qrCodeIcon.png
    - assets/img/serviceIcon.png
    - assets/img/termsIcon.png
    - assets/img/logo2.png
    - assets/img/filters.png
    - assets/img/delate.png
    - assets/img/favorite.png
    - assets/img/thumbDown.png
    - assets/img/thumbUp.png
    - assets/img/qrcode.png
    - assets/img/del.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900

  - family: Montserrat
    fonts:
        - asset : assets/fonts/Montserrat-Regular.ttf
        - asset : assets/fonts/Montserrat-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
flutter_intl:
  enabled: true

dependency_overrides:
  intl: 0.17.0-nullsafety.2

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
